# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/s2eghbali/Desktop/nbt/nbt-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/s2eghbali/Desktop/nbt/nbt-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s2eghbali/Desktop/nbt/nbt-master/CMakeFiles /home/s2eghbali/Desktop/nbt/nbt-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s2eghbali/Desktop/nbt/nbt-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nbt

# Build rule for target.
nbt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nbt
.PHONY : nbt

# fast build rule for target.
nbt/fast:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/build
.PHONY : nbt/fast

src/loadVar.o: src/loadVar.cpp.o

.PHONY : src/loadVar.o

# target to build an object file
src/loadVar.cpp.o:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/loadVar.cpp.o
.PHONY : src/loadVar.cpp.o

src/loadVar.i: src/loadVar.cpp.i

.PHONY : src/loadVar.i

# target to preprocess a source file
src/loadVar.cpp.i:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/loadVar.cpp.i
.PHONY : src/loadVar.cpp.i

src/loadVar.s: src/loadVar.cpp.s

.PHONY : src/loadVar.s

# target to generate assembly for a file
src/loadVar.cpp.s:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/loadVar.cpp.s
.PHONY : src/loadVar.cpp.s

src/node.o: src/node.cpp.o

.PHONY : src/node.o

# target to build an object file
src/node.cpp.o:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/node.cpp.o
.PHONY : src/node.cpp.o

src/node.i: src/node.cpp.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.cpp.i:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/node.cpp.i
.PHONY : src/node.cpp.i

src/node.s: src/node.cpp.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.cpp.s:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/node.cpp.s
.PHONY : src/node.cpp.s

src/root_node.o: src/root_node.cpp.o

.PHONY : src/root_node.o

# target to build an object file
src/root_node.cpp.o:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/root_node.cpp.o
.PHONY : src/root_node.cpp.o

src/root_node.i: src/root_node.cpp.i

.PHONY : src/root_node.i

# target to preprocess a source file
src/root_node.cpp.i:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/root_node.cpp.i
.PHONY : src/root_node.cpp.i

src/root_node.s: src/root_node.cpp.s

.PHONY : src/root_node.s

# target to generate assembly for a file
src/root_node.cpp.s:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/src/root_node.cpp.s
.PHONY : src/root_node.cpp.s

test_create_tree.o: test_create_tree.cpp.o

.PHONY : test_create_tree.o

# target to build an object file
test_create_tree.cpp.o:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/test_create_tree.cpp.o
.PHONY : test_create_tree.cpp.o

test_create_tree.i: test_create_tree.cpp.i

.PHONY : test_create_tree.i

# target to preprocess a source file
test_create_tree.cpp.i:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/test_create_tree.cpp.i
.PHONY : test_create_tree.cpp.i

test_create_tree.s: test_create_tree.cpp.s

.PHONY : test_create_tree.s

# target to generate assembly for a file
test_create_tree.cpp.s:
	$(MAKE) -f CMakeFiles/nbt.dir/build.make CMakeFiles/nbt.dir/test_create_tree.cpp.s
.PHONY : test_create_tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nbt"
	@echo "... src/loadVar.o"
	@echo "... src/loadVar.i"
	@echo "... src/loadVar.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/root_node.o"
	@echo "... src/root_node.i"
	@echo "... src/root_node.s"
	@echo "... test_create_tree.o"
	@echo "... test_create_tree.i"
	@echo "... test_create_tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

